config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'answers#index'
  resources :users, only: [:index, :show, :create] do
    resources :answers, only: [:index, :show, :new, :create, :delete]
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :answers, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def index
    @answers = Answer.all
  end
  def show
    @answer = Answer.find(params[:id])
  end
  def new
    @answer = Answer.new
  end
  def create
    @answer = Answer.new(answer_params)

  end
  def answer_params
    params.require(:house).require(:owner).permit(
      :name,
      :text_content
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @answers = @user.answers
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/index.html.erb
<h1>IA Mateo</h1>
<h2>Création part Mateo Ceron Arana</h2>
<h4>
  Posez vos questions
</h4>

<% @answers.each do |answer| %>
  <p>
    <%= answer.name %>
  </p>
  <p>
    <%= answer.text_content %>
    (<%= answer.created_at.strftime("%d/%m/%Y") %>)
  </p>
  <div class="test">
    <p>Hello world</p>
  </div>
<% end %>
<script src="//cdnjs.cloudflare.com/ajax/libs/annyang/2.6.1/annyang.min.js"></script>
<script>
if (annyang) {
    const testFor = document.querySelector('.test');
    var commands = {
        'Bonjour': function() {
          testFor.insertAdjacentHTML('beforeend', '<p>bonjour ann ju</p>');
        }
      };

      // Add our commands to annyang
    // annyang.addCallback('result', function(phrases) {
    // const a = ("test1: ", phrases[0]);
    // const b = ("test2: ", phrases);
    // const c = a + b
    // const d = `<p>${c}</p>`
    // const testFor = document.querySelector('.test');
    // testFor.insertAdjacentHTML('beforeend', a);
  //});

  // Add our commands to annyang
  annyang.addCommands(commands);
  // annyang.addCallback('result')
  annyang.setLanguage('fr-FR');

  // Start listening.
  annyang.start({autoRestart: true, continuous: true });
  annyang.debug([newState=true]);

}
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/users/index.html.erb
<%= @user %>

app/views/users/show.html.erb
<h1>
  Hello
  <%= @user.first_name %> <%= @user.last_name %>
</h1>
<p>
  Accéder à ses mémos:
</p>
<%= link_to "answer", user_answers_path(@user) %>